<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc13a1fa613708e987ffc9762e29e1bb6
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc13a1fa613708e987ffc9762e29e1bb6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc13a1fa613708e987ffc9762e29e1bb6::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
